/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lab5.h"

bool_t
xdr_int_pair(XDR *xdrs, int_pair *objp)
{

	if (!xdr_int(xdrs, &objp->a))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->b))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_two_strings(XDR *xdrs, two_strings *objp)
{

	if (!xdr_string(xdrs, &objp->s1, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->s2, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_int_array(XDR *xdrs, int_array *objp)
{

	if (!xdr_array(xdrs, (char **)&objp->int_array_val, (u_int *)&objp->int_array_len, ~0, sizeof(int), (xdrproc_t)xdr_int))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_arr_stats(XDR *xdrs, arr_stats *objp)
{

	if (!xdr_int(xdrs, &objp->max))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->min))
		return (FALSE);
	if (!xdr_double(xdrs, &objp->avg))
		return (FALSE);
	return (TRUE);
}
