/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LAB5_H_RPCGEN
#define _LAB5_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct int_pair {
	int a;
	int b;
};
typedef struct int_pair int_pair;
#ifdef __cplusplus
extern "C" bool_t xdr_int_pair(XDR *, int_pair*);
#elif __STDC__
extern  bool_t xdr_int_pair(XDR *, int_pair*);
#else /* Old Style C */
bool_t xdr_int_pair();
#endif /* Old Style C */


struct two_strings {
	char *s1;
	char *s2;
};
typedef struct two_strings two_strings;
#ifdef __cplusplus
extern "C" bool_t xdr_two_strings(XDR *, two_strings*);
#elif __STDC__
extern  bool_t xdr_two_strings(XDR *, two_strings*);
#else /* Old Style C */
bool_t xdr_two_strings();
#endif /* Old Style C */


typedef struct {
	u_int int_array_len;
	int *int_array_val;
} int_array;
#ifdef __cplusplus
extern "C" bool_t xdr_int_array(XDR *, int_array*);
#elif __STDC__
extern  bool_t xdr_int_array(XDR *, int_array*);
#else /* Old Style C */
bool_t xdr_int_array();
#endif /* Old Style C */


struct arr_stats {
	int max;
	int min;
	double avg;
};
typedef struct arr_stats arr_stats;
#ifdef __cplusplus
extern "C" bool_t xdr_arr_stats(XDR *, arr_stats*);
#elif __STDC__
extern  bool_t xdr_arr_stats(XDR *, arr_stats*);
#else /* Old Style C */
bool_t xdr_arr_stats();
#endif /* Old Style C */


#define LAB5_PROG ((rpc_uint)0x31230055)
#define LAB5_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define IS_PALINDROME ((rpc_uint)1)
extern "C" int * is_palindrome_1(char **, CLIENT *);
extern "C" int * is_palindrome_1_svc(char **, struct svc_req *);
#define IS_LEAP_YEAR ((rpc_uint)2)
extern "C" int * is_leap_year_1(int *, CLIENT *);
extern "C" int * is_leap_year_1_svc(int *, struct svc_req *);
#define GCD ((rpc_uint)3)
extern "C" int * gcd_1(int_pair *, CLIENT *);
extern "C" int * gcd_1_svc(int_pair *, struct svc_req *);
#define SQUARE_ROOT ((rpc_uint)4)
extern "C" double * square_root_1(double *, CLIENT *);
extern "C" double * square_root_1_svc(double *, struct svc_req *);
#define SWAP_NO_TEMP ((rpc_uint)5)
extern "C" int_pair * swap_no_temp_1(int_pair *, CLIENT *);
extern "C" int_pair * swap_no_temp_1_svc(int_pair *, struct svc_req *);
#define ARRAY_STATS ((rpc_uint)6)
extern "C" arr_stats * array_stats_1(int_array *, CLIENT *);
extern "C" arr_stats * array_stats_1_svc(int_array *, struct svc_req *);
#define COMPARE_STRINGS ((rpc_uint)7)
extern "C" int * compare_strings_1(two_strings *, CLIENT *);
extern "C" int * compare_strings_1_svc(two_strings *, struct svc_req *);
#define IS_SUBSTRING ((rpc_uint)8)
extern "C" int * is_substring_1(two_strings *, CLIENT *);
extern "C" int * is_substring_1_svc(two_strings *, struct svc_req *);
#define CONCATENATE ((rpc_uint)9)
extern "C" char ** concatenate_1(two_strings *, CLIENT *);
extern "C" char ** concatenate_1_svc(two_strings *, struct svc_req *);
#define REVERSE_ARRAY ((rpc_uint)10)
extern "C" int_array * reverse_array_1(int_array *, CLIENT *);
extern "C" int_array * reverse_array_1_svc(int_array *, struct svc_req *);

#elif __STDC__
#define IS_PALINDROME ((rpc_uint)1)
extern  int * is_palindrome_1(char **, CLIENT *);
extern  int * is_palindrome_1_svc(char **, struct svc_req *);
#define IS_LEAP_YEAR ((rpc_uint)2)
extern  int * is_leap_year_1(int *, CLIENT *);
extern  int * is_leap_year_1_svc(int *, struct svc_req *);
#define GCD ((rpc_uint)3)
extern  int * gcd_1(int_pair *, CLIENT *);
extern  int * gcd_1_svc(int_pair *, struct svc_req *);
#define SQUARE_ROOT ((rpc_uint)4)
extern  double * square_root_1(double *, CLIENT *);
extern  double * square_root_1_svc(double *, struct svc_req *);
#define SWAP_NO_TEMP ((rpc_uint)5)
extern  int_pair * swap_no_temp_1(int_pair *, CLIENT *);
extern  int_pair * swap_no_temp_1_svc(int_pair *, struct svc_req *);
#define ARRAY_STATS ((rpc_uint)6)
extern  arr_stats * array_stats_1(int_array *, CLIENT *);
extern  arr_stats * array_stats_1_svc(int_array *, struct svc_req *);
#define COMPARE_STRINGS ((rpc_uint)7)
extern  int * compare_strings_1(two_strings *, CLIENT *);
extern  int * compare_strings_1_svc(two_strings *, struct svc_req *);
#define IS_SUBSTRING ((rpc_uint)8)
extern  int * is_substring_1(two_strings *, CLIENT *);
extern  int * is_substring_1_svc(two_strings *, struct svc_req *);
#define CONCATENATE ((rpc_uint)9)
extern  char ** concatenate_1(two_strings *, CLIENT *);
extern  char ** concatenate_1_svc(two_strings *, struct svc_req *);
#define REVERSE_ARRAY ((rpc_uint)10)
extern  int_array * reverse_array_1(int_array *, CLIENT *);
extern  int_array * reverse_array_1_svc(int_array *, struct svc_req *);

#else /* Old Style C */
#define IS_PALINDROME ((rpc_uint)1)
extern  int * is_palindrome_1();
extern  int * is_palindrome_1_svc();
#define IS_LEAP_YEAR ((rpc_uint)2)
extern  int * is_leap_year_1();
extern  int * is_leap_year_1_svc();
#define GCD ((rpc_uint)3)
extern  int * gcd_1();
extern  int * gcd_1_svc();
#define SQUARE_ROOT ((rpc_uint)4)
extern  double * square_root_1();
extern  double * square_root_1_svc();
#define SWAP_NO_TEMP ((rpc_uint)5)
extern  int_pair * swap_no_temp_1();
extern  int_pair * swap_no_temp_1_svc();
#define ARRAY_STATS ((rpc_uint)6)
extern  arr_stats * array_stats_1();
extern  arr_stats * array_stats_1_svc();
#define COMPARE_STRINGS ((rpc_uint)7)
extern  int * compare_strings_1();
extern  int * compare_strings_1_svc();
#define IS_SUBSTRING ((rpc_uint)8)
extern  int * is_substring_1();
extern  int * is_substring_1_svc();
#define CONCATENATE ((rpc_uint)9)
extern  char ** concatenate_1();
extern  char ** concatenate_1_svc();
#define REVERSE_ARRAY ((rpc_uint)10)
extern  int_array * reverse_array_1();
extern  int_array * reverse_array_1_svc();
#endif /* Old Style C */

#endif /* !_LAB5_H_RPCGEN */
