apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab9-pv
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/lab9-pv-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab9-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
