apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
  labels:
    app: pvc-test
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: lab9-storage
          mountPath: /data
  volumes:
    - name: lab9-storage
      persistentVolumeClaim:
        claimName: lab9-pvc
