/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct calc_input {
	double a;
	double b;
	int op;
};
typedef struct calc_input calc_input;

typedef struct {
	u_int int_array_len;
	int *int_array_val;
} int_array;

#define ADD_PROG 0x4562877
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FACTORIAL 1
extern  quad_t * factorial_1(int *, CLIENT *);
extern  quad_t * factorial_1_svc(int *, struct svc_req *);
#define CALCULATE 2
extern  double * calculate_1(calc_input *, CLIENT *);
extern  double * calculate_1_svc(calc_input *, struct svc_req *);
#define IS_PRIME 3
extern  int * is_prime_1(int *, CLIENT *);
extern  int * is_prime_1_svc(int *, struct svc_req *);
#define FIBONACCI 4
extern  char ** fibonacci_1(int *, CLIENT *);
extern  char ** fibonacci_1_svc(int *, struct svc_req *);
#define MAX_IN_ARRAY 5
extern  int * max_in_array_1(int_array *, CLIENT *);
extern  int * max_in_array_1_svc(int_array *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FACTORIAL 1
extern  quad_t * factorial_1();
extern  quad_t * factorial_1_svc();
#define CALCULATE 2
extern  double * calculate_1();
extern  double * calculate_1_svc();
#define IS_PRIME 3
extern  int * is_prime_1();
extern  int * is_prime_1_svc();
#define FIBONACCI 4
extern  char ** fibonacci_1();
extern  char ** fibonacci_1_svc();
#define MAX_IN_ARRAY 5
extern  int * max_in_array_1();
extern  int * max_in_array_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_calc_input (XDR *, calc_input*);
extern  bool_t xdr_int_array (XDR *, int_array*);

#else /* K&R C */
extern bool_t xdr_calc_input ();
extern bool_t xdr_int_array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
