/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

bool_t
xdr_calc_input (XDR *xdrs, calc_input *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->op))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_int_array (XDR *xdrs, int_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->int_array_val, (u_int *) &objp->int_array_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
